name: base

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - cmake
  - compilers
  - jupyter
  - matplotlib
  - pynvim
  - numpy
  - pandas
  - pandoc
  - "python>=3.12"
  - python-lsp-server
  - seaborn
  - tqdm
  - ruff
  - fortls
  - findent
