name: stats

channels:
  - conda-forge
  - nodefaults

dependencies:
  - dask
  - numba
  - pyarrow
  - pyro-ppl
  - scipy
  - scikit-learn
  - statsmodels
  - xarray
  - zarr
  - gpytorch
  - "cudatoolkit>=11"
  - "pytorch=*=cpu*"
