format = """
$all $fill $time $line_break $character
"""

"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol = "[?](bold green) "

[username]
show_always = true

[hostname]
ssh_only = false

[conda]
ignore_base = false

[fill]
symbol = " "

[time]
disabled = false
use_12hr = true
format = "[$time]($style)"
style = "bright-black"

