format = """
$all $fill $cmd_duration $time $line_break $character
"""

"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol = "[?](bold purple) "

[username]
disabled = true

[hostname]
ssh_only = false

[conda]
ignore_base = false

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow)"

[fill]
symbol = " "

[time]
disabled = false
use_12hr = true
format = "[$time]($style)"
style = "bright-black"

